### ISSUE TITLE
Error while downloading mit1003

### ISSUE THREAD

**Issue by VadymBoikov** [matthias-k/pysaliency#8] opened 2018-04-10 14:07 UTC
Hi!
I'm using  function to download mit1003 dataset using command.
`mit1003_stimuli, mit1003_fixations = pysaliency.get_mit1003(location='test_datasets_py3')`

and I'm getting following error (Tried on macOS & Ubuntu with Octave) :

>   scalar structure containing the fields:
> 
>     file: 1x40 sq_string
>     name: 1x21 sq_string
>     line: 1x1 scalar
>     column: 1x1 scalar
>     scope: 1x1 scalar
>     context: 1x1 scalar
> __ERROR__
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/vadym/.conda/envs/pysaliency3/lib/python3.6/site-packages/pysaliency/external_datasets.py", line 350, in get_mit1003
>     run_matlab_cmd('extract_all_fixations;', cwd=temp_dir)
>   File "/home/vadym/.conda/envs/pysaliency3/lib/python3.6/site-packages/pysaliency/utils.py", line 256, in run_matlab_cmd
>     sp.check_call([matlab] + args, cwd=cwd)
>   File "/home/vadym/.conda/envs/pysaliency3/lib/python3.6/subprocess.py", line 291, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['/usr/bin/octave', '--traditional', '--eval', "try;extract_all_fixations;;catch exc;disp(lasterror);for i=1:size(lasterror.stack);disp(lasterror.stack(i));end;disp('__ERROR__');exit(1);end;quit"]' returned non-zero exit status 1.

**Comment by matthias-k** [comment] 2018-05-01 16:14
Hi @VadymBoikov ,

thankyou for your bug report. I can reproduce your error when using octave. When matlab is available, downloading MIT1003 works without problems. Therefore I suspect an incompatibility in octave that was added since I wrote this code (back then it worked with octave). I would love to debug this, but octave makes it nearly impossible to just get a good stack stack trace of the exception. This too worked better a few years ago, when octave printed the value of the fields in the stack trace. I tried for some time now to get the stack trace back but octave is refusing to print anything helpful. I will try some more things but I'm running out of ideas (and to be honest I'm not too motivated to spend my time on figuring out all the different places where octave behaves differently than matlab).

Best,
  Matthias

**Comment by matthias-k** [comment] 2018-05-01 16:51
Hi @VadymBoikov I finally managed to get a proper stack trace (I will change the octave call to include this). Apparently the call of `median` in the MIT1003 function `checkFixations.m` (line 292) is incompatible with octave. I assume the script is running into [this octave bug](https://savannah.gnu.org/bugs/?48690). It has not seen any activity lately so I suspect it won't be fixed anytime soon. In general octave doesn't work for most of the models included in pysaliency because of similar inconsistencies. I'm sorry for this but I can't fix octave ;). Do you have access to matlab?

I'm closing this since it's not a bug in pysaliency.

**Closed by matthias-k** 2018-05-01 16:51 UTC

**Comment by vadym-wix** [comment] 2018-05-02 06:45
Thanks @matthias-k for thorough investigation! :)

Unfortunately, I don't have access to matlab, Is there MIT dataset stored  anywhere in format other than matlab, maybe python pickled or anything else? If it is preprocessed, it will be also fine for me

**Comment by VadymBoikov** [comment] 2018-05-02 06:47
Thanks @matthias-k for thorough investigation! :)

Unfortunately, I don't have access to matlab, Is there MIT dataset stored anywhere in format other than matlab, maybe python pickled or anything else? If it is preprocessed, it will be also fine for me

**Comment by matthias-k** [comment] 2018-05-02 14:51
@VadymBoikov as it happens, I recently implemented hdf5 import and export for stimuli and fixations to make them better portable (I had a few nasty experiences with pickle files in the past. Even pickles from python 3.5 can fail in python 3.6...). I give you the files for MIT1003. Since I'm not sure whether I can share them publicly, I will send you an email with the details. In the meantime, you will need to update you pysaliency installation to have access to the new hdf5 methods.

**Comment by manooshsamiei76** [comment] 2020-12-02 04:35
Hello,
I am encountering the same issue on google colab. I cannot install matlab on colab, as I dont have root priviledge. I am wondering if you could help me on this. 
Thank you.
